module.exports = {
    "CleanTask": require("./CleanTask"),
    "RevTask": require("./RevTask"),
    "DocTask": require("./DocTask"),
    "HintTask": require("./HintTask"),
    "PreBuildTask": require("./PreBuildTask"),
    "PostBuildTask": require("./PostBuildTask"),
    "ViewsTask": require("./ViewsTask"),
    "ImagesTask": require("./ImagesTask"),
    "AssetsTask": require("./AssetsTask"),
    "ServeTask": require("./ServeTask"),
    "ManifestTask": require("./ManifestTask"),
    "ComplexityTask": require("./ComplexityTask"),
    "TestTask": require("./TestTask"),
    "WatchTestTask": require("./WatchTestTask"),
    "WatchBuildTask": require("./WatchBuildTask"),
    "BrowserifyTask": require("./BrowserifyTask"),
    "StylesTask": require("./StylesTask"),
    "BuildTask": require("./BuildTask"),
    "TargetsTask": require("./TargetsTask"),
    "ListingTask": require("./ListingTask"),
    "ScaffoldingTask": require("./ScaffoldingTask")
};