module.exports = {
    "CleanTask": require("./build/CleanTask"),
    "RevTask": require("./build/RevTask"),
    "PreBuildTask": require("./hooks/PreBuildTask"),
    "PostBuildTask": require("./hooks/PostBuildTask"),
    "RebundleTask": require("./hooks/RebundleTask"),
    "ViewsTask": require("./build/ViewsTask"),
    "ImagesTask": require("./build/ImagesTask"),
    "AssetsTask": require("./build/AssetsTask"),
    "ServeTask": require("./build/ServeTask"),
    "ManifestTask": require("./build/ManifestTask"),
    "TestTask": require("./test/TestTask"),
    "WatchBuildTask": require("./build/WatchBuildTask"),
    "JSTask": require("./build/JSTask"),
    "StylesTask": require("./build/StylesTask"),
    "BuildTask": require("./build/BuildTask"),
    "ListingTask": require("./extra/ListingTask"),
    "ScaffoldingTask": require("./extra/ScaffoldingTask"),
    "NodeWatchBuildTask": require('./nodejs/NodeWatchBuildTask'),
    "TranspileTSTask": require('./build/TranspileTSTask')
};