#!/usr/bin/env node

var smild = require('../'), //Init smild
    program = require('commander'),
    packageJson = require('../package.json');

program
    .version(packageJson.version)
    .option('-r, --release', 'Enable release mode')
    .option('-m, --module', 'Creates a module on scaffolding')
    .arguments('<command> [target]')
    .action(function (command, target) {
        smild.buildHelper.setTarget(target || "main");
        smild.buildHelper.isRelease(program.release || false);
        smild.buildHelper.setModule(program.module || false);
        smild.taskRunner.run(command);
    });

program.parse(process.argv);