#!/usr/bin/env node

var program = require('commander'),
    packageJson = require('../package.json'),
    command = null,
    target = null,
    gulp = require('gulp'),
    _ = require('lodash'),
    chalk = require('chalk');

program
    .version(packageJson.version)
    .option('-r, --release', 'Enable release mode')
    .option('-m, --module', 'Creates a module on scaffolding')
    .arguments('<command> [target]')
    .action(function (_command, _target) {
        command = _command || "tasks";
        target = _target || "main"
    })
    .parse(process.argv);

//Environment variables to be injected also in smildfile
process.env.TARGET = target;
process.env.DEBUG = !program.release;

var smild = require('../'); //Init smild

if (command && _.indexOf(gulp.tree(), command) < 0) {
    console.log(chalk.red(command, "task not found."));
    console.log();
    console.log("Available tasks:");
    console.log();
    command = "tasks";
}

smild.buildHelper.setTarget(target);
smild.buildHelper.isRelease(program.release || false);
smild.buildHelper.setModule(program.module || false);
smild.taskRunner.run(command);