#!/usr/bin/env node

var smild = require('../'), //Init smild
    commander = require('commander'),
    packageJson = require('../package.json');

commander
    .version(packageJson.version)
    .option('-r, --release', 'Enable release mode')
    .arguments('<command> [target]')
    .action(function (command, target) {
        smild.buildHelper.setTarget(target || "main");
        smild.buildHelper.isRelease(options.release || false);
        taskRunner.run()
    });

commander.parse(process.argv);